// LOCALHOST 
### Get all contacts GET http://localhost:8080/contacts

### Get contact by id GET http://localhost:8080/contacts/65a60dddc88ca384b22d9e9d

### Create contact POST http://localhost:8080/contacts

{

    "firstName": "Becca", "lastName": "Manning", "email": "BManning22@gmail.com", "favoriteColor": "Yellow", "birthday": "01/19/2003"

}

### PUT contact PUT http://localhost:8080/contacts/6220bcb39cd507e920c75a0b

{
    "firstName": "Becca", "lastName": "Manning", "email": "Newmail@gmail.com", "favoriteColor": "Pink", "birthday": "05/22/2005"
} 

### DELETE contact DELETE http://localhost:8080/contacts/6220b775099269ff7b31ceab


// PRODUCTION Deploy 
### Get all contacts GET https://week4service.onrender.com/contacts

### Get contact by id GET https://week4service.onrender.com/contacts/622023f642f9ab4cd6e060b3

### Create contact POST https://week4service.onrender.com/contacts

{
"firstName": "Becca", "lastName": "Manning", "email": "BManning22@gmail.com", "favoriteColor": "Yellow", "birthday": "01/19/2003"
}

### PUT contact PUT https://week4service.onrender.com/contacts/6220bcb39cd507e920c75a0b

{
"firstName": "Becca", "lastName": "Manning", "email": "Newmail@gmail.com", "favoriteColor": "Pink", "birthday": "05/22/2005"
}

### DELETE contact DELETE https://week4service.onrender.com/contacts/6220e34083149913680f9a64